### ISSUE TITLE
About vsec-harborbay/Security Access Level 3

### ISSUE THREAD

**Issue by yichen115** [pwnalone/bhctf#1]
Hi, how did you find out that vsec-harborbay/Security Access Level 3 "the key is computed as the bitwise complement of the seed"? I can't see anything. 🥹

**Comment by pwnalone** [comment]
IIRC, this challenge required a bit of guess work, as it is not immediately obvious what is meant when we are asked to authenticate "using MAAATH". As I mentioned in the write-up, I just tried out different things and found the solution after a few attempts; however, if none of my manual attempts were successful, I would have written a Python script to brute-force the particular math operation(s) they were using to generate the key.

I'm going to close this issue out, but feel free to message me on Discord if you have any follow-up questions.
