### ISSUE TITLE
Pwn-WebServerWoes extracting canary, frame pointer, return address required too many requests resulting in crashing the container

### ISSUE THREAD

**Issue by trungchubao** [pwnalone/bhctf#2]
Hi, the write-ups are wonderful! Highly greatly appreciate your work. Many lessons learned! Regarding the WebServerWoes challenge, as I'm practicing in BH Proving Ground, your script couldn't run to its end. Because the number of requests needed to extract those sort of information crash the container. Didn't you face similar problem in the CTF Season 1? Do you have any suggestion for a workaround?

Thank you!

**Comment by pwnalone** [comment]
I've been going back through these challenges in preparation for season 2, and I am experiencing the same issue. I did not encounter this problem in season 1, and the script in this repository is the exact one that I used to solve the challenge last year. Obviously I can't know exactly why my solution from last year is not working anymore, but my best guess is that more stringent resource limitations have been placed on the containers that are launched for this challenge (e.g. shorter lifetimes, fewer processes that can be spawned, etc.).

I've already reported this issue privately to BlockHarbor's staff and they are looking it.
